config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: [:index, :show]
  resources :users, only: [:show]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'  
  }

  root to: "photos#index"
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @user = @photo.user
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:body, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <p>
    <strong>Body:</strong>
    <%= photo.body %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= photo.image %>
  </p>

</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<h1>Lista de Fotos</h1>
<ul>
  <% @photos.each do |photo| %>
    <li>
      <%= link_to photo.caption, photo_path(photo) %>
      Subido por: <%= link_to photo.user.name, user_path(photo.user) %>
    </li>
  <% end %>
</ul>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<h2><%= @photo.caption %></h2>
<p>Subido por: <%= link_to @user.name, user_path(@user) %></p>
<p>Foto de perfil: <%= image_tag @user.profile_picture %></p>r